# Generated by Django 4.2.16 on 2026-03-18 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Ngày học')),
                ('session_number', models.IntegerField(default=1, verbose_name='Buổi thứ')),
                ('topic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nội dung buổi học')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='courses.classroom', verbose_name='Lớp học')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Buổi điểm danh',
                'verbose_name_plural': 'Buổi điểm danh',
                'db_table': 'attendance_sessions',
                'ordering': ['-session_date'],
                'unique_together': {('classroom', 'session_date', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng'), ('late', 'Đi trễ'), ('excused', 'Có phép')], default='present', max_length=10, verbose_name='Trạng thái')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession', verbose_name='Buổi học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.student', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
                'db_table': 'attendance',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
