# Generated by Django 4.2.16 on 2026-04-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='notes',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='absence_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lý do vắng'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_excused',
            field=models.BooleanField(default=False, verbose_name='Có phép'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Có mặt'), ('absent', 'Vắng')], default='present', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
