# Generated by Django 4.2.16 on 2026-03-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='languages',
            field=models.CharField(blank=True, help_text='Ví dụ: Tiếng Anh, Tiếng Nhật (ngăn cách bằng dấu phẩy)', max_length=200, null=True, verbose_name='Ngôn ngữ giảng dạy'),
        ),
    ]
