# Generated by Django 4.2.16 on 2026-04-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quê quán'),
        ),
    ]
