# Generated by Django 4.2.16 on 2026-03-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khóa học')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã khóa học')),
                ('language', models.CharField(choices=[('english', 'Tiếng Anh'), ('japanese', 'Tiếng Nhật'), ('korean', 'Tiếng Hàn'), ('chinese', 'Tiếng Trung'), ('french', 'Tiếng Pháp'), ('german', 'Tiếng Đức'), ('other', 'Khác')], default='english', max_length=20, verbose_name='Ngôn ngữ')),
                ('level', models.CharField(choices=[('beginner', 'Sơ cấp'), ('elementary', 'Cơ bản'), ('intermediate', 'Trung cấp'), ('upper_intermediate', 'Trung cấp cao'), ('advanced', 'Cao cấp')], default='beginner', max_length=30, verbose_name='Trình độ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('duration_weeks', models.IntegerField(default=12, verbose_name='Thời lượng (tuần)')),
                ('total_hours', models.IntegerField(default=36, verbose_name='Tổng số giờ')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Học phí')),
                ('max_students', models.IntegerField(default=30, verbose_name='Số HV tối đa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang mở')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Khóa học',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên lớp')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã lớp')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phòng học')),
                ('schedule', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lịch học')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('upcoming', 'Sắp khai giảng'), ('active', 'Đang học'), ('completed', 'Đã kết thúc'), ('cancelled', 'Đã hủy')], default='upcoming', max_length=20, verbose_name='Trạng thái')),
                ('max_students', models.IntegerField(default=30, verbose_name='Số HV tối đa')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='courses.course', verbose_name='Khóa học')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='accounts.teacher', verbose_name='Giảng viên')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'db_table': 'classes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('completed', 'Hoàn thành'), ('dropped', 'Đã nghỉ'), ('suspended', 'Tạm nghỉ')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm cuối')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.classroom', verbose_name='Lớp học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Đăng ký lớp',
                'verbose_name_plural': 'Đăng ký lớp',
                'db_table': 'enrollments',
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
