# Generated by Django 4.2.16 on 2026-03-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='learning_mode',
            field=models.CharField(choices=[('offline', 'Tại trung tâm (Offline)'), ('online', 'Trực tuyến (Online)')], default='offline', max_length=20, verbose_name='Hình thức học'),
        ),
    ]
