# Generated by Django 4.2.16 on 2026-03-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_classroom_learning_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu'),
        ),
    ]
