# Generated by Django 4.2.16 on 2026-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_classroom_end_time_classroom_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_lessons',
            field=models.IntegerField(default=24, verbose_name='Số tiết học'),
        ),
    ]
