# Generated by Django 4.2.16 on 2026-03-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_total_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='total_lessons',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số tiết học'),
        ),
    ]
