# Generated by Django 4.2.16 on 2026-03-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_classroom_total_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_hours',
        ),
    ]
