# Generated by Django 4.2.16 on 2026-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_duration_weeks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='final_grade',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='attendance_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm chuyên cần (10%)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='final_test_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm cuối kỳ (70%)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='midterm_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Điểm giữa kỳ (20%)'),
        ),
    ]
