# Generated by Django 4.2.16 on 2026-04-15 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_user_gender'),
        ('courses', '0008_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái duyệt'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số tiền đặt cọc'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('deposited', 'Đã đặt cọc'), ('paid', 'Đã thanh toán đủ')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200, verbose_name='Tên bài Test')),
                ('test_type', models.CharField(choices=[('midterm', 'Giữa kỳ'), ('final', 'Cuối kỳ'), ('quiz', 'Kiểm tra ngắn'), ('oral', 'Kiểm tra miệng'), ('practice', 'Bài tập thực hành'), ('other', 'Khác')], default='quiz', max_length=20, verbose_name='Loại bài Test')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Điểm')),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Điểm tối đa')),
                ('test_date', models.DateField(verbose_name='Ngày thi/kiểm tra')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='courses.classroom', verbose_name='Lớp học')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người nhập')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='accounts.student', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Điểm Test',
                'verbose_name_plural': 'Điểm Test',
                'db_table': 'test_scores',
                'ordering': ['test_date'],
            },
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='attendance_grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='final_test_grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='midterm_grade',
        ),
    ]
