# Generated by Django 4.2.16 on 2026-04-24 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('file', models.FileField(upload_to='materials/%Y/%m/', verbose_name='Tệp đính kèm')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word'), ('xls', 'Excel'), ('ppt', 'PowerPoint'), ('image', 'Hình ảnh'), ('video', 'Video'), ('audio', 'Âm thanh'), ('archive', 'File nén'), ('other', 'Khác')], default='other', max_length=10, verbose_name='Loại tệp')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Kích thước (bytes)')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Tên file gốc')),
                ('download_count', models.IntegerField(default=0, verbose_name='Lượt tải')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.classroom', verbose_name='Lớp học')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Tài liệu bài giảng',
                'verbose_name_plural': 'Tài liệu bài giảng',
                'db_table': 'course_materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
