# Generated by Django 4.2.16 on 2026-05-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_merge_coursematerial_scholarship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AlterModelTable(
            name='blogpost',
            table=None,
        ),
    ]
