# Generated by Django 4.2.16 on 2026-03-18 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giảm giá')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Thành tiền')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản'), ('card', 'Thẻ'), ('other', 'Khác')], default='cash', max_length=20, verbose_name='Phương thức')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('overdue', 'Quá hạn'), ('refunded', 'Đã hoàn tiền'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn thanh toán')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.enrollment', verbose_name='Đăng ký lớp')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.student', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
